// <auto-generated />
using System;
using Lamas_Victor_ComicsWPF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lamas_Victor_ComicsWPF.Migrations
{
    [DbContext(typeof(ComicsDbContext))]
    [Migration("20250111103237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClienteDetalleOperacionVlt", b =>
                {
                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<int>("DetalleOperacionId")
                        .HasColumnType("int")
                        .HasColumnName("Detalle_OperacionID");

                    b.HasKey("ClienteId", "DetalleOperacionId")
                        .HasName("PK__Cliente___7C08759048B1115E");

                    b.HasIndex("DetalleOperacionId");

                    b.ToTable("Cliente_Detalle_Operacion_VLT", (string)null);
                });

            modelBuilder.Entity("ClienteVltDetalleOperacion", b =>
                {
                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("DetalleOperacionId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId", "DetalleOperacionId");

                    b.ToTable("ClienteVltDetalleOperacion");
                });

            modelBuilder.Entity("EmpleadoLocal", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("LocalId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId", "LocalId");

                    b.ToTable("EmpleadoLocal");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AutorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorId"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AutorId")
                        .HasName("PK__Autor__F58AE909D7162F75");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.ClienteVlt", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("NIF");

                    b.Property<string>("Nombre")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("ClienteId")
                        .HasName("PK__Cliente___71ABD0A77955C3D5");

                    b.ToTable("Cliente_VLT");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Comic", b =>
                {
                    b.Property<int>("ComicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComicID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComicId"));

                    b.Property<int?>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("AutorID");

                    b.Property<int?>("EditorialId")
                        .HasColumnType("int")
                        .HasColumnName("EditorialID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("PrecioCompra")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_Compra");

                    b.Property<decimal?>("PrecioVenta")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_Venta");

                    b.HasKey("ComicId")
                        .HasName("PK__Comic__B8F0904E8A3A6A41");

                    b.HasIndex("AutorId");

                    b.HasIndex("EditorialId");

                    b.ToTable("Comic");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.DetalleOperacion", b =>
                {
                    b.Property<int>("DetalleOperacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Detalle_OperacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleOperacionId"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ComicId")
                        .HasColumnType("int")
                        .HasColumnName("ComicID");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(7, 4)");

                    b.Property<int>("OperacionId")
                        .HasColumnType("int")
                        .HasColumnName("OperacionID");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("DetalleOperacionId")
                        .HasName("PK__Detalle___DA3A53712B71632B");

                    b.HasIndex("ComicId");

                    b.HasIndex("OperacionId");

                    b.ToTable("Detalle_Operacion");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Editorial", b =>
                {
                    b.Property<int>("EditorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EditorialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EditorialId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("EditorialId")
                        .HasName("PK__Editoria__D54C828EEF5736FC");

                    b.ToTable("Editorial");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmpleadoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<string>("Activo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_baja");

                    b.Property<byte[]>("Fotografia")
                        .HasColumnType("image")
                        .HasColumnName("Fotografia");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("NIF");

                    b.Property<string>("Nombre")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Password")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("EmpleadoId")
                        .HasName("PK__Empleado__958BE6F037E7C2E3");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Local", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalId"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("LocalId")
                        .HasName("PK__Local__499359DB2FD37C88");

                    b.ToTable("Local");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.MedioDePago", b =>
                {
                    b.Property<int>("MedioDePagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Medio_De_PagoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedioDePagoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreCorto")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("Nombre_Corto");

                    b.HasKey("MedioDePagoId")
                        .HasName("PK__Medio_De__BBFD276345FA8C6B");

                    b.ToTable("Medio_De_Pago");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Operacion", b =>
                {
                    b.Property<int>("OperacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OperacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperacionId"));

                    b.Property<int>("ComicId")
                        .HasColumnType("int")
                        .HasColumnName("ComicID");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("EmpleadoID");

                    b.Property<DateTime>("FechaOperacion")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Operacion");

                    b.Property<int>("LocalId")
                        .HasColumnType("int")
                        .HasColumnName("LocalID");

                    b.Property<int>("MedioDePagoId")
                        .HasColumnType("int")
                        .HasColumnName("Medio_De_PagoID");

                    b.Property<int>("TipoOperacionId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_OperacionID");

                    b.HasKey("OperacionId")
                        .HasName("PK__Operacio__8A668AF7E6681174");

                    b.HasIndex("ComicId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("LocalId");

                    b.HasIndex("MedioDePagoId");

                    b.HasIndex("TipoOperacionId");

                    b.ToTable("Operacion");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.StockComic", b =>
                {
                    b.Property<int>("StockComicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Stock_ComicID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockComicId"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("ComicId")
                        .HasColumnType("int")
                        .HasColumnName("ComicID");

                    b.Property<int>("LocalId")
                        .HasColumnType("int")
                        .HasColumnName("LocalID");

                    b.HasKey("StockComicId")
                        .HasName("PK__Stock_Co__3A77E09345362F02");

                    b.HasIndex("ComicId");

                    b.HasIndex("LocalId");

                    b.ToTable("Stock_Comic");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.TipoOperacion", b =>
                {
                    b.Property<int>("TipoOperacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_OperacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoOperacionId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("TipoOperacionId")
                        .HasName("PK__Tipo_Ope__F75BE529F01C44F8");

                    b.ToTable("Tipo_Operacion");
                });

            modelBuilder.Entity("LocalEmpleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("EmpleadoID");

                    b.Property<int>("LocalId")
                        .HasColumnType("int")
                        .HasColumnName("LocalID");

                    b.HasKey("EmpleadoId", "LocalId")
                        .HasName("PK__Local_Em__3112D36D14020CFE");

                    b.HasIndex("LocalId");

                    b.ToTable("Local_Empleado", (string)null);
                });

            modelBuilder.Entity("ClienteDetalleOperacionVlt", b =>
                {
                    b.HasOne("Lamas_Victor_ComicsWPF.Model.ClienteVlt", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__Cliente_D__Clien__5CD6CB2B");

                    b.HasOne("Lamas_Victor_ComicsWPF.Model.DetalleOperacion", null)
                        .WithMany()
                        .HasForeignKey("DetalleOperacionId")
                        .IsRequired()
                        .HasConstraintName("FK__Cliente_D__Detal__5DCAEF64");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Comic", b =>
                {
                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Autor", "Autor")
                        .WithMany("Comics")
                        .HasForeignKey("AutorId")
                        .HasConstraintName("FK__Comic__AutorID__286302EC");

                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Editorial", "Editorial")
                        .WithMany("Comics")
                        .HasForeignKey("EditorialId")
                        .HasConstraintName("FK__Comic__Editorial__29572725");

                    b.Navigation("Autor");

                    b.Navigation("Editorial");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.DetalleOperacion", b =>
                {
                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Comic", "Comic")
                        .WithMany("DetalleOperaciones")
                        .HasForeignKey("ComicId")
                        .IsRequired()
                        .HasConstraintName("FK__Detalle_O__Comic__4316F928");

                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Operacion", "Operacion")
                        .WithMany("DetalleOperaciones")
                        .HasForeignKey("OperacionId")
                        .IsRequired()
                        .HasConstraintName("FK__Detalle_O__Opera__4222D4EF");

                    b.Navigation("Comic");

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Operacion", b =>
                {
                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Comic", "Comic")
                        .WithMany("Operaciones")
                        .HasForeignKey("ComicId")
                        .IsRequired()
                        .HasConstraintName("FK__Operacion__Comic__3D5E1FD2");

                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Empleado", "Empleado")
                        .WithMany("Operaciones")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Operacion__Emple__3F466844");

                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Local", "Local")
                        .WithMany("Operaciones")
                        .HasForeignKey("LocalId")
                        .IsRequired()
                        .HasConstraintName("FK__Operacion__Local__3E52440B");

                    b.HasOne("Lamas_Victor_ComicsWPF.Model.MedioDePago", "MedioDePago")
                        .WithMany("Operaciones")
                        .HasForeignKey("MedioDePagoId")
                        .IsRequired()
                        .HasConstraintName("FK__Operacion__Medio__3B75D760");

                    b.HasOne("Lamas_Victor_ComicsWPF.Model.TipoOperacion", "TipoOperacion")
                        .WithMany("Operaciones")
                        .HasForeignKey("TipoOperacionId")
                        .IsRequired()
                        .HasConstraintName("FK__Operacion__Tipo___3C69FB99");

                    b.Navigation("Comic");

                    b.Navigation("Empleado");

                    b.Navigation("Local");

                    b.Navigation("MedioDePago");

                    b.Navigation("TipoOperacion");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.StockComic", b =>
                {
                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Comic", "Comic")
                        .WithMany("StockComics")
                        .HasForeignKey("ComicId")
                        .IsRequired()
                        .HasConstraintName("FK__Stock_Com__Comic__34C8D9D1");

                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Local", "Local")
                        .WithMany("StockComics")
                        .HasForeignKey("LocalId")
                        .IsRequired()
                        .HasConstraintName("FK__Stock_Com__Local__33D4B598");

                    b.Navigation("Comic");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("LocalEmpleado", b =>
                {
                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Empleado", null)
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Local_Emp__Emple__300424B4");

                    b.HasOne("Lamas_Victor_ComicsWPF.Model.Local", null)
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .IsRequired()
                        .HasConstraintName("FK__Local_Emp__Local__30F848ED");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Autor", b =>
                {
                    b.Navigation("Comics");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Comic", b =>
                {
                    b.Navigation("DetalleOperaciones");

                    b.Navigation("Operaciones");

                    b.Navigation("StockComics");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Editorial", b =>
                {
                    b.Navigation("Comics");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Empleado", b =>
                {
                    b.Navigation("Operaciones");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Local", b =>
                {
                    b.Navigation("Operaciones");

                    b.Navigation("StockComics");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.MedioDePago", b =>
                {
                    b.Navigation("Operaciones");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.Operacion", b =>
                {
                    b.Navigation("DetalleOperaciones");
                });

            modelBuilder.Entity("Lamas_Victor_ComicsWPF.Model.TipoOperacion", b =>
                {
                    b.Navigation("Operaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
